language: python
python: 2.7
sudo: false
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
before_install:
  - python --version
  - pip --version
  - uname -a
  - lsb_release -a
script:
  - py.test --cov=src
notifications:
  email:
    on_success: never
    on_failure: always

